---
# Name your file secrets.yml

development:
  # Infrastructure 
  DB_FILENAME: db/local/dev.db
  INSTAGRAM_TOKEN: create_instagram_api_token
  ACCOUNT_ID: create_instagram_account_id
  API_HOST: http://localhost:9090

app_test:
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/test.db
  API_HOST: http://localhost:9090

test:
  # Infrastructure 
  DB_FILENAME: db/local/test.db
  INSTAGRAM_TOKEN: create_instagram_api_token
  ACCOUNT_ID: create_instagram_account_id
  API_HOST: http://localhost:9090

production:
  # Infrastructure
  # - assign DATABASE_URL in production
  INSTAGRAM_TOKEN: create_instagram_api_token
  ACCOUNT_ID: create_instagram_account_id
  API_HOST: https://taggie-api
