---
# Name your file secrets.yml

development:
  DB_FILENAME: db/local/dev.db
  INSTAGRAM_TOKEN: EAAJRl6PP8gYBO5Pwx2bxNkl2w9EsWWsIkozAZClASZAeeCxrw1WsaNvDjh0bUroAAuHczKVAyBdWSUgYJyjwl7NiUd3JUGb8yJ3hkpVENpZB1asHq7MfY6P8VWtZASpY4TWhmcZBaycvZCHvSRw0nhH91fcJRZAww5fnJWYtAawEyqGDG50yl5jjNC3
  ACCOUNT_ID: "17841462175987660"

test:
  DB_FILENAME: db/local/test.db
  INSTAGRAM_TOKEN: EAAJRl6PP8gYBO5Pwx2bxNkl2w9EsWWsIkozAZClASZAeeCxrw1WsaNvDjh0bUroAAuHczKVAyBdWSUgYJyjwl7NiUd3JUGb8yJ3hkpVENpZB1asHq7MfY6P8VWtZASpY4TWhmcZBaycvZCHvSRw0nhH91fcJRZAww5fnJWYtAawEyqGDG50yl5jjNC3
  ACCOUNT_ID: "17841462175987660"

production:
  INSTAGRAM_TOKEN: EAAJRl6PP8gYBO5Pwx2bxNkl2w9EsWWsIkozAZClASZAeeCxrw1WsaNvDjh0bUroAAuHczKVAyBdWSUgYJyjwl7NiUd3JUGb8yJ3hkpVENpZB1asHq7MfY6P8VWtZASpY4TWhmcZBaycvZCHvSRw0nhH91fcJRZAww5fnJWYtAawEyqGDG50yl5jjNC3
  ACCOUNT_ID: "17841462175987660"