---
# Name your file secrets.yml

development:
  DB_FILENAME: db/local/dev.db
  INSTAGRAM_TOKEN: create_instagram_api_token
  ACCOUNT_ID: create_instagram_account_id
  API_HOST: http://localhost:9090
  REDIS_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>

app_test:
  DB_FILENAME: db/local/test.db
  API_HOST: http://localhost:9090
  REDIS_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>

test: 
  DB_FILENAME: db/local/test.db
  INSTAGRAM_TOKEN: create_instagram_api_token
  ACCOUNT_ID: create_instagram_account_id
  API_HOST: http://localhost:9090
  REDIS_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>

production:
  # - assign DATABASE_URL in production
  INSTAGRAM_TOKEN: create_instagram_api_token
  ACCOUNT_ID: create_instagram_account_id
  API_HOST: https://taggie-api-2f98ea7d6ebb.herokuapp.com/
  REDIS_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>
